{
  "node_id": "MDM6VGFnODMwNzM5MTo4YTZlOWI3MjI5YTVjYTI1ZTRhNGRkMWRmZDBmZDU4N2UyYTA3YjA3",
  "sha": "8a6e9b7229a5ca25e4a4dd1dfd0fd587e2a07b07",
  "url": "https://api.github.com/repos/mahmoud/boltons/git/tags/8a6e9b7229a5ca25e4a4dd1dfd0fd587e2a07b07",
  "tagger": {
    "name": "Mahmoud Hashemi",
    "email": "mahmoud@hatnote.com",
    "date": "2015-04-10T22:01:16Z"
  },
  "object": {
    "sha": "8de26dbadbcf88d78488e1dc966645b2f5be9a79",
    "type": "commit",
    "url": "https://api.github.com/repos/mahmoud/boltons/git/commits/8de26dbadbcf88d78488e1dc966645b2f5be9a79"
  },
  "tag": "0.6.0",
  "message": "Python 3 support and several community bugfixes. Docs clarification on TracebackInfo\n",
  "verification": {
    "verified": false,
    "reason": "unsigned",
    "signature": null,
    "payload": null
  }
}
